### ISSUE TITLE
windows project create failed

### ISSUE THREAD

**Issue by JacobSobolev** [NatWeiss/RapidGame#45]
C:\Users\Jacob\Desktop>npm install rapidgame -g
C:\Users\Jacob\AppData\Roaming\npm\rapidgame -> C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\bin\rapidgame
rapidgame@1.0.1 C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame
├── commander@2.2.0
├── winreg@0.0.12
├── path-extra@1.0.3
├── node-uuid@1.4.7
├── wrench@1.5.8
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── replace@0.2.10 (colors@0.5.1, nomnom@1.6.2, minimatch@0.2.14)
├── universal-analytics@0.3.10 (async@0.2.10, underscore@1.8.3, request@2.69.0)
└── download@4.4.3 (gulp-rename@1.2.2, object-assign@4.0.1, is-url@1.2.1, each-async@1.1.1, stream-combiner2@1.1.1, concat-stream@1.5.1, readable-stream@2.0.5, vinyl@1.1.1, read-all-stream@3.1.0, filenamify@1.2.0, ware@1.3.0, got@5.4.1, caw@1.2.0, vinyl-fs@2.3.1, gulp-decompress@1.2.0)

C:\Users\Jacob\Desktop>rapidgame create cocos2dx "HeckYeah" org.myorg.heckyeah
Rapidly creating a game
Engine: Cocos2dx
Template: TwoScene
Copying project files
C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\node_modules\wrench\lib\wrench.js:249
        if (e.code !== 'EEXIST') throw e;
                                 ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Jacob\.rapidgame\3.9\HeckYeah'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.exports.copyDirSyncRecursive (C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\node_modules\wrench\lib\wrench.js:246:12)
    at copyRecursive (C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\rapidgame.js:1447:9)
    at Command.createProject (C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\rapidgame.js:332:14)
    at Command.<anonymous> (C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\node_modules\commander\index.js:249:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\node_modules\commander\index.js:478:12)
    at Command.parse (C:\Users\Jacob\AppData\Roaming\npm\node_modules\rapidgame\node_modules\commander\index.js:370:21)

C:\Users\Jacob\Desktop>

**Comment by NatWeiss** [comment]
Fixed in version 1.0.2.
